CBDEMO-122

diff --git a/.cloudbees/workflows/buildanddeploy.yaml b/.cloudbees/workflows/buildanddeploy.yaml
--- a/.cloudbees/workflows/buildanddeploy.yaml
+++ b/.cloudbees/workflows/buildanddeploy.yaml
@@ -2,8 +2,9 @@ apiVersion: automation.cloudbees.io/v1alpha1
 kind: workflow
 name: build_and_deploy
 on:
-  push:
+  pull_request:
     branches:
+      - ashok
       - main
 jobs:
   Build:
@@ -11,6 +12,7 @@ jobs:
       unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
       commit_id: ${{ steps.commitinfo.outputs.commit_id }}
       commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
+      jira_key: ${{ steps.commitinfo.outputs.jira_key }}
     steps:
       - name: Configure git
         uses: docker://alpine/git:latest
@@ -24,9 +26,16 @@ jobs:
         run: |
           COMMIT_ID=$(git rev-parse HEAD)
           COMMIT_MSG=$(git log -1 --pretty=%B)
+          # Extract the JIRA issue key (assuming format like PROJECTKEY-123)
+          JIRA_KEY=$(echo "$COMMIT_MSG" | grep -oE "[A-Z]+-[0-9]+")
+          if [ -z "$JIRA_KEY" ]; then
+            echo "Error: Commit message must include a valid JIRA issue key." >&2
+            exit 1
+          fi
 
           echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
           echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
+          echo "jira_key=${JIRA_KEY}" >> $CLOUDBEES_OUTPUTS/jira_key
       - uses: docker://maven:3-eclipse-temurin-17
         name: Build
         kind: build
@@ -60,6 +69,7 @@ jobs:
             - **Commit Message:** "${{ steps.commitinfo.outputs.commit_msg }}"
             ## Unit Test Results
             - **Unit Test Results:** "${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}"
+            - **JIRA Issue Key:** "${{ steps.commitinfo.outputs.jira_key }}"
   StaticAnalysis:
     outputs:
       BLOCKER_COUNT: ${{ steps.FetchSonarQubeIssues.outputs.BLOCKER_COUNT }}
@@ -180,9 +190,7 @@ jobs:
       - name: Publish Ingress IP Evidence
         uses: cloudbees-io/publish-evidence-item@v1
         with:
-          content: |
+          content: |+
             ## Deployment Information
-
              - **Ingress IP:** "${{ steps.getIngressIP.outputs.ingress_ip }}/config"
 
-             - **Ingress IP:** "${{ steps.getIngressIP.outputs.ingress_ip }}/config"
