CBDEMO-122

diff --git a/.cloudbees/workflows/buildanddeploy.yaml b/.cloudbees/workflows/buildanddeploy.yaml
--- a/.cloudbees/workflows/buildanddeploy.yaml
+++ b/.cloudbees/workflows/buildanddeploy.yaml
@@ -7,12 +7,29 @@ on:
       - ashok
       - main
 jobs:
+  CheckMergeability:
+    steps:
+      - name: Checkout
+        uses: cloudbees-io/checkout@v1
+      - name: Check if PR is Mergable
+        id: check_mergeable
+        uses: docker://alpine/git:latest
+        run: |
+          MERGEABLE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/cashokannamalai/configserver1/pulls/${{ github.event.pull_request.number }} | jq .mergeable)
+          if [ "$MERGEABLE" = "false" ]; then
+            echo "Error: Pull request is not mergable. Please resolve conflicts."
+            exit 1
+          else
+            echo "PR is mergable. Continuing workflow."
+          fi
   Build:
+    needs: CheckMergeability 
     outputs:
-      unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
-      commit_id: ${{ steps.commitinfo.outputs.commit_id }}
-      commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
-      jira_key: ${{ steps.commitinfo.outputs.jira_key }}
+        unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
+        commit_id: ${{ steps.commitinfo.outputs.commit_id }}
+        commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
+        jira_key: ${{ steps.commitinfo.outputs.jira_key }}
     steps:
       - name: Configure git
         uses: docker://alpine/git:latest
